package server

import (
	"encoding/json"
	"os"
	"testing"

	"github.com/stretchr/testify/require"

	"phasionary/internal/domain"
	"phasionary/internal/journal"
)

// testdata/web-ops.json is generated by `npm run fixtures` in web/.
type webFixture struct {
	Ops      []journal.Op     `json:"ops"`
	Projects []domain.Project `json:"projects"`
	Deleted  []string         `json:"deleted"`
}

func TestWebClientOpsRebuildTheSameProject(t *testing.T) {
	raw, err := os.ReadFile("testdata/web-ops.json")
	require.NoError(t, err)
	var fixture webFixture
	require.NoError(t, json.Unmarshal(raw, &fixture))
	require.NotEmpty(t, fixture.Ops)

	env := newEnv(t)
	device := env.enroll("web")
	for i := range fixture.Ops {
		fixture.Ops[i].DeviceID = device.id
	}

	resp := env.sync(device, fixture.Ops)
	for _, want := range fixture.Projects {
		snap := findSnapshot(t, resp, want.ID)
		require.NotNil(t, snap.Project, "project %s came back deleted", want.ID)
		require.Equal(t, want, *snap.Project)
	}
	for _, id := range fixture.Deleted {
		require.True(t, findSnapshot(t, resp, id).Deleted, "project %s should be tombstoned", id)
	}
}
